gateway:
  ip: 172.18.0.5
token:
  expiration_time: 86400000
  

---

spring:
  profiles: dev

token:
  secret: user_token_dev_rabbitmq_test
  
---

spring:
  profiles: prod
  
token:
  secret: user_token_prod