gateway:
  ip: 192.168.1.39
token:
  expiration_time: 86400000
  

---

spring:
  profiles: dev

token:
  secret: user_token_dev_rabbitmq_test
  
---

spring:
  profiles: prod
  
token:
  secret: user_token_prod